{{- if .Values.backendRuntime.enabled -}}
apiVersion: inference.llmaz.io/v1alpha1
kind: BackendRuntime
metadata:
  labels:
    app.kubernetes.io/name: backendruntime
    app.kubernetes.io/part-of: llmaz
    app.kubernetes.io/created-by: llmaz
  name: sglang
spec:
  commands:
    - python3
    - -m
    - sglang.launch_server
  image: lmsysorg/sglang
  version: v0.2.10-cu121
  args:
    - mode: Default
      flags:
        - --model-path
        - "{{`{{ .ModelPath }}`}}"
        - --served-model-name
        - "{{`{{ .ModelName }}`}}"
        - --host
        - "0.0.0.0"
        - --port
        - "8080"
  resources:
    requests:
      cpu: 4
      memory: 8Gi
    limits:
      cpu: 4
      memory: 8Gi
{{- end }}
